### ISSUE TITLE
xplr hangs after hitting enter in map mode

### ISSUE THREAD

**Issue by blob42** [sayanarijit/map.xplr#2]
This happend with all operations on map mode when I hit enter xplr hangs

![2022-10-04-000312_1022x473_scrot](https://user-images.githubusercontent.com/210457/193694095-4633a4f0-4b82-4079-b4f6-3ccb382f4858.png)

**Comment by sayanarijit** [comment]
Need more info. Could you please post a link to your xplr config? Also, os version and terminal you're using.

**Comment by blob42** [comment]
I found the reason, it's related to fish shell and starting xplr as a keybinding on fish. 

On bash shell it works. 
On fish it works if I start by typing xplr.

However when I use a fish keybinding to start xplr, map commands hang on output. I have other interactive tuis like fzf which don't expose this behavior.

If you want to test/debug you can install fish shell and put a keybinding in `XDG_CONFIG_DIR/fish/config.fish` like this one: 

`bind -M insert \ex  'xplr'`

After after running a map command that produces output, the screen will hang at [press ENTER ...]

I am using, latest version of xplr and map on Arch Linux. I am also using `fish` as shell command but I have the same problem if I use `bash` as shell command for xplr.

**Comment by blob42** [comment]
I found a fix, I keep it here if someone else encounters the same issue:

So to use a keybinding from fish shell with xplr this is the binding that worked for me:

`bind -M insert \ex 'fish -i -c xplr; commandline -f repaint'`
