### ISSUE TITLE
Selection should be retained when exiting map mode

### ISSUE THREAD

**Issue by fredcallaway** [sayanarijit/map.xplr#4]
Title is self-explanatory. Is there a technical reason this is difficult?

**Comment by sayanarijit** [comment]
Hi, didn't think of a usecase, so didn't implement it yet. But it should be easy to implement with a setup argument `keep_selection = true`.

**Comment by fredcallaway** [comment]
I think the main use cases would be noticing you accidentally added (or forgot to add) a file. Perhaps you’re more fastidious than I ;)

**Comment by sayanarijit** [comment]
You're probably right. But it depends. A question: what do you think should be the ideal behaviour after copying a list of files to a different location using `:sc`? Clear the selection or keep it? The current default behaviour (probably unreleased) is to keep only the files on which the cp command failed and clear the rest (previously it was to clear the selection regardless of the result). But that's difficult to implement for map.xplr, specially for the single map mode.

Also what you think should happen when renaming files? Clear the selection? Keep the renamed files selected (difficult for map.xplr)?

One approach would be to implement the following:

~enter = clear the selection,~ esc = keep the selection, except the moved files. I.e. not be consistent with `:sc` copying.

What do you think?

**Comment by fredcallaway** [comment]
I think a good global rule that you could apply to both map and :sc is to keep the selection, only removing files that no longer exist (because the command moved them). I can see why your :sc behavior is desirable, but I think consistency is more important.

**Comment by sayanarijit** [comment]
Makes some sense. Let's try that.
