### ISSUE TITLE
Request: add an index/counter placeholder

### ISSUE THREAD

**Issue by andrejcremoznik** [sayanarijit/map.xplr#8]
Would be cool to have an `{idx}` placeholder for every iteration.

So you could do `mv {} file-{idx}.{ext}` and rename everything to the same name with a number.

Additionally, and I don't know how much this would complicate things, having a left-padded, offset adjustable, incrementing counter would be ideal.

For example, if you know you're looping through 987 files, you'd ideally want a 3 character long counter starting at `001` and ending on `987`. Maybe something like `{idx+X, Y}` where `idx` = iteration, `X` = custom offset (simple addition to the counter) and `Y` is the length of the string to 0-pad to.  So `{idx+3, 5}` would give `00003`, `00004`, ... `09876` and so on.

**Comment by sayanarijit** [comment]
Idx seems easy... Prefix padding can also be done with some ease based on the number of files (as opposed to user input). But I'd leave the custom padding and calculations to the user's skills with their favourite $EDITOR.
